// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import "dotenv/config";
import { defineConfig } from '@prisma/config';

if (!process.env.DATABASE_URL) {
  console.error("DATABASE_URL is not defined in your .env file!");
}

export default defineConfig({
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
